### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by danielagadens** [ocefpaf/CursoPython_AlunasJu#2]
Tentei instalar os programas em casa, porém estou em dúvidas sobre o que digitar após abrir o anaconda prompt.
Seriam essas as linhas de comando?

conda config --add channels conda-forge --force
conda env create --file environment.yml

**Comment by ocefpaf** [comment]
> Tentei instalar os programas em casa, porém estou em dúvidas sobre o que digitar após abrir o anaconda prompt.
> Seriam essas as linhas de comando?
> 
> conda config --add channels conda-forge --force
> conda env create --file environment.yml

Correto. Mas tente essas, nessa ordem, aqui só por segurança:

```
conda config --add channels conda-forge --force
conda update --all --yes
conda env create --file environment.yml
```

A primeira linha adiciona o canal da comunidade do conda-forge que tem muitos mais pacotes que o padrão. A segunda faz uma atualização antes de instalar o ambiente do curso. E a última faz a instalação do ambiente do curso.

Qq coisa manda as mensagens de erro aqui. Boa sorte!

**Comment by danielagadens** [comment]
![image](https://user-images.githubusercontent.com/48091015/54157149-7db57200-4426-11e9-89fa-8b2c1ee53d70.png)

**Comment by ocefpaf** [comment]
@danielagadens checa o conteúdo do arquivo `environment.yml` e vê se está igual a isso:

```yaml
name: LabJu
channels:
  - conda-forge
dependencies:
  - python=3.7
  - altair
  - animatplot
  - bokeh
  - geopandas
  - hvplot
  - jupyter
  - jupyterthemes
  - matplotlib
  - nb_conda_kernels
  - numpy
  - palettable
  - pandas
  - rise
  - scikit-learn
  - scipy
  - seaborn
  - vega
  - vega_datasets
  - windrose
  - xarray
  - xlrd
```

Caso seja tente:

```
conda env create --file environment.yml --name LabJu
```
